######################################################################
# Automatically generated by qmake (2.01a) dom feb 24 15:58:19 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hw.cpp


