#!/bin/bash
":"; exec emacs -Q  --script "$0" -f main -- "$@" # -*-emacs-lisp-*-

(defun main ()
  (mapc 'cat-file (cdr argv))
  (kill-emacs))
  

(defun cat-file (filename)
  (send-string-to-terminal
   (with-temp-buffer
     (insert-file-contents filename)
     (buffer-string))))
